name: Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  testnet-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - run: yarn build-contract
      - run: yarn install
      - run: yarn build
        env:
          CI: false
          REACT_APP_STAGE: development
          REACT_APP_INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          REACT_APP_FILTER_MARKETS: 1

      - run: npx ipfs-deploy@v11.2.2 build -u c4rex --quiet > /tmp/ipfs.txt
      - run: gh pr comment -b "https://cloudflare-ipfs.com/ipfs/$(cat /tmp/ipfs.txt)" "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
